- name: install EPEL
  package:
    name: epel-release
  become: true
- name: install tinyproxy
  package:
    name: tinyproxy
  become: true
- name: enable the tinyproxy service
  systemd:
    name: tinyproxy
    state: started
    enabled: yes
  become: true
- copy:
    dest: /etc/tinyproxy/tinyproxy.conf
    content: |
      User tinyproxy
      Group tinyproxy
      Port 8888
      Timeout 60
      DefaultErrorFile "/usr/share/tinyproxy/default.html"
      StatFile "/usr/share/tinyproxy/stats.html"
      LogFile "/var/log/tinyproxy/tinyproxy.log"
      LogLevel Info
      PidFile "/var/run/tinyproxy/tinyproxy.pid"
      MaxClients 100
      MinSpareServers 15
      MaxSpareServers 60
      StartServers 20
      MaxRequestsPerChild 0
      ViaProxyName "tinyproxy"
      ConnectPort 443
  become: true
  notify: restart tinyproxy
